// Maps full team names (as returned by The Odds API) to the short
// abbreviations this app displays on game cards. Keyed lowercase.
const RAW: Record<string, string> = {
  // NFL
  "arizona cardinals": "ARI",
  "atlanta falcons": "ATL",
  "baltimore ravens": "BAL",
  "buffalo bills": "BUF",
  "carolina panthers": "CAR",
  "chicago bears": "CHI",
  "cincinnati bengals": "CIN",
  "cleveland browns": "CLE",
  "dallas cowboys": "DAL",
  "denver broncos": "DEN",
  "detroit lions": "DET",
  "green bay packers": "GB",
  "houston texans": "HOU",
  "indianapolis colts": "IND",
  "jacksonville jaguars": "JAX",
  "kansas city chiefs": "KC",
  "las vegas raiders": "LV",
  "los angeles chargers": "LAC",
  "los angeles rams": "LAR",
  "miami dolphins": "MIA",
  "minnesota vikings": "MIN",
  "new england patriots": "NE",
  "new orleans saints": "NO",
  "new york giants": "NYG",
  "new york jets": "NYJ",
  "philadelphia eagles": "PHI",
  "pittsburgh steelers": "PIT",
  "san francisco 49ers": "SF",
  "seattle seahawks": "SEA",
  "tampa bay buccaneers": "TB",
  "tennessee titans": "TEN",
  "washington commanders": "WAS",

  // NBA
  "atlanta hawks": "ATL",
  "boston celtics": "BOS",
  "brooklyn nets": "BKN",
  "charlotte hornets": "CHA",
  "chicago bulls": "CHI",
  "cleveland cavaliers": "CLE",
  "dallas mavericks": "DAL",
  "denver nuggets": "DEN",
  "detroit pistons": "DET",
  "golden state warriors": "GSW",
  "houston rockets": "HOU",
  "indiana pacers": "IND",
  "la clippers": "LAC",
  "los angeles clippers": "LAC",
  "los angeles lakers": "LAL",
  "memphis grizzlies": "MEM",
  "miami heat": "MIA",
  "milwaukee bucks": "MIL",
  "minnesota timberwolves": "MIN",
  "new orleans pelicans": "NOP",
  "new york knicks": "NYK",
  "oklahoma city thunder": "OKC",
  "orlando magic": "ORL",
  "philadelphia 76ers": "PHI",
  "phoenix suns": "PHX",
  "portland trail blazers": "POR",
  "sacramento kings": "SAC",
  "san antonio spurs": "SAS",
  "toronto raptors": "TOR",
  "utah jazz": "UTA",
  "washington wizards": "WAS",

  // MLB
  "arizona diamondbacks": "ARI",
  "atlanta braves": "ATL",
  "baltimore orioles": "BAL",
  "boston red sox": "BOS",
  "chicago cubs": "CHC",
  "chicago white sox": "CWS",
  "cincinnati reds": "CIN",
  "cleveland guardians": "CLE",
  "colorado rockies": "COL",
  "detroit tigers": "DET",
  "houston astros": "HOU",
  "kansas city royals": "KC",
  "los angeles angels": "LAA",
  "los angeles dodgers": "LAD",
  "miami marlins": "MIA",
  "milwaukee brewers": "MIL",
  "minnesota twins": "MIN",
  "new york mets": "NYM",
  "new york yankees": "NYY",
  "oakland athletics": "ATH",
  athletics: "ATH",
  "philadelphia phillies": "PHI",
  "pittsburgh pirates": "PIT",
  "san diego padres": "SD",
  "san francisco giants": "SF",
  "seattle mariners": "SEA",
  "st louis cardinals": "STL",
  "st. louis cardinals": "STL",
  "tampa bay rays": "TB",
  "texas rangers": "TEX",
  "toronto blue jays": "TOR",
  "washington nationals": "WSH",

  // NHL
  "anaheim ducks": "ANA",
  "utah hockey club": "UTA",
  "utah mammoth": "UTA",
  "boston bruins": "BOS",
  "buffalo sabres": "BUF",
  "calgary flames": "CGY",
  "carolina hurricanes": "CAR",
  "chicago blackhawks": "CHI",
  "colorado avalanche": "COL",
  "columbus blue jackets": "CBJ",
  "dallas stars": "DAL",
  "detroit red wings": "DET",
  "edmonton oilers": "EDM",
  "florida panthers": "FLA",
  "los angeles kings": "LAK",
  "minnesota wild": "MIN",
  "montreal canadiens": "MTL",
  "nashville predators": "NSH",
  "new jersey devils": "NJD",
  "new york islanders": "NYI",
  "new york rangers": "NYR",
  "ottawa senators": "OTT",
  "philadelphia flyers": "PHI",
  "pittsburgh penguins": "PIT",
  "san jose sharks": "SJS",
  "seattle kraken": "SEA",
  "st louis blues": "STL",
  "st. louis blues": "STL",
  "tampa bay lightning": "TBL",
  "toronto maple leafs": "TOR",
  "vancouver canucks": "VAN",
  "vegas golden knights": "VGK",
  "washington capitals": "WSH",
  "winnipeg jets": "WPG",

  // MLS
  "atlanta united fc": "ATL",
  "austin fc": "ATX",
  "charlotte fc": "CLT",
  "chicago fire fc": "CHI",
  "fc cincinnati": "CIN",
  "colorado rapids": "COL",
  "columbus crew": "CLB",
  "d.c. united": "DC",
  "dc united": "DC",
  "fc dallas": "DAL",
  "houston dynamo fc": "HOU",
  "houston dynamo": "HOU",
  "sporting kansas city": "SKC",
  "la galaxy": "LA",
  "los angeles galaxy": "LA",
  "los angeles fc": "LAFC",
  "inter miami cf": "MIA",
  "inter miami": "MIA",
  "minnesota united fc": "MIN",
  "minnesota united": "MIN",
  "cf montreal": "MTL",
  "cf montréal": "MTL",
  "nashville sc": "NSH",
  "new england revolution": "NE",
  "new york city fc": "NYC",
  "new york red bulls": "RBNY",
  "orlando city sc": "ORL",
  "philadelphia union": "PHI",
  "portland timbers": "POR",
  "real salt lake": "RSL",
  "san diego fc": "SD",
  "san jose earthquakes": "SJ",
  "seattle sounders fc": "SEA",
  "st. louis city sc": "STL",
  "st louis city sc": "STL",
  "toronto fc": "TOR",
  "vancouver whitecaps fc": "VAN",

  // La Liga
  alaves: "ALA",
  "deportivo alaves": "ALA",
  "athletic bilbao": "ATH",
  "athletic club": "ATH",
  "atletico madrid": "ATM",
  "atlético madrid": "ATM",
  barcelona: "BAR",
  "fc barcelona": "BAR",
  "real betis": "BET",
  "celta vigo": "CEL",
  celta: "CEL",
  espanyol: "ESP",
  "rcd espanyol": "ESP",
  getafe: "GET",
  girona: "GIR",
  "las palmas": "LPA",
  leganes: "LEG",
  leganés: "LEG",
  mallorca: "MAL",
  "real mallorca": "MAL",
  osasuna: "OSA",
  "rayo vallecano": "RAY",
  "real madrid": "RMA",
  "real sociedad": "RSO",
  sevilla: "SEV",
  valencia: "VAL",
  "real valladolid": "VLL",
  villarreal: "VIL",
};

export function teamAbbreviation(fullName: string): string {
  const known = RAW[fullName.trim().toLowerCase()];
  if (known) return known;
  // Fallback: initials of each word, so an unmapped team still renders
  // something reasonable instead of crashing the ingest.
  return fullName
    .split(/\s+/)
    .map((w) => w[0])
    .join("")
    .slice(0, 3)
    .toUpperCase();
}
